steps:

  - id: "Executando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

  - id: "Chown in /var/www"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['exec', '-u', 'root', '-t', 'app', 'chown', '-R', 'www-data:www-data', '/var/www']

  - id: "Executando composer"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['exec', '-t', 'app', 'composer', 'install']

  - id: "Copiando .env"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

  - id: "Rodando key:generate"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']

  - id: "Executando migrations"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate']

  - id: "Executando phpunit"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']

  - id: "Construindo imagem a partir do Dockerfile.prod"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

  - id: "Enviando imagem para o image registry"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['push', 'gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA']
