version: '2.4'

services:

  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - 8000:80
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      app:
        condition: service_started

  redis:
    image: redis:6.0.6-alpine3.12
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

  db:
    build: .docker/mysql
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - 3303:3306
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 15s
      timeout: 15s
      retries: 3

networks:
  app-network:
    driver: bridge
