FROM php:7.4.8-fpm-alpine3.12

RUN apk add --no-cache openssl shadow bash mysql-client \
    && docker-php-ext-install pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www
RUN rm -rf html
RUN ln -s public html

COPY . .

RUN composer install --optimize-autoloader --no-dev \
    && php artisan cache:clear \
    && chmod -R 777 storage/

EXPOSE 9000

ENTRYPOINT ["php-fpm"]
